name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        build-type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }}
      
    - name: test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build-type }}
